### ISSUE TITLE
Feedback on "io.vertx:vertx-oracle-client" and 19c database?

### ISSUE THREAD

**Issue by u-ways** [d53dave/oracle-cursor-leak-vertx#1]
Hello,

Sorry to open a not so related issue. I am interested into using `vertx:vertx-oracle-client` and 19c database in production.  Do you mind sharing your experience with this? Any issues or considerations?

Kind Regards,
U.

**Comment by d53dave** [comment]
No worries. 

Quick backstory: I created this repo as a reproducer for [an issue](https://github.com/eclipse-vertx/vertx-sql-client/issues/1187) we ran into when integrating Oracle support into our Vert.x-based product.

We are generally very happy with Vert.x, and the team always responded quickly to the issues we found. They were quick with the fix for this issue, too.

Regarding the Vert.x Oracle support: it's still a slightly moving target. The teams is working on the drivers, for example the SSL support was added recently and documentation followed just a few days ago. I will say that, generally, most things are working fine for us, and we didn't find any other driver issues (other than the one which we reported and which was fixed).

We've had numerous issues that didn't stem from the Vert.x driver: Oracle doesn't care too much about SQL standards and often behaves in strange (Oracle-specific) ways. Maintaining a product that supports several DB-vendors is a lot of work, and supporting Oracle makes it even harder.

**Comment by u-ways** [comment]
> We are generally very happy with Vert.x, and the team always responded quickly to the issues we found. They were quick with the fix for this issue, too.

We are having a good experience with Vert.x so far, too.

 > Regarding the Vert.x Oracle support: it's still a slightly moving target. The teams is working on the drivers, for example the SSL support was added recently and documentation followed just a few days ago. I will say that, generally, most things are working fine for us, and we didn't find any other driver issues (other than the one which we reported and which was fixed).

I see, yeah documentation was quite minimal for the Oracle client and that was the main factor to dig deeper.

> We've had numerous issues that didn't stem from the Vert.x driver: Oracle doesn't care too much about SQL standards and often behaves in strange (Oracle-specific) ways. 

I agree, fortunately for us we only needed to support Oracle. 

> Maintaining a product that supports several DB-vendors is a lot of work, and supporting Oracle makes it even harder.

Ouch, I hope you guys are currently happy with the cross-vendor solution at hand.

Thank you so much for your response @d53dave
